### ISSUE TITLE
publish the docker image as a package

### ISSUE THREAD

**Issue by codefromthecrypt** [JonasKunz/cpu-burner#2]
I'd like to use this demo in k3s without building the image locally, `docker save`, etc to load it. Do you mind publishing this image to as a github package, so that it can be retrieved by a public OCI url?

**Comment by JonasKunz** [comment]
Here you go:
https://github.com/JonasKunz/cpu-burner/pkgs/container/cpu-burner

**Comment by codefromthecrypt** [comment]
love it
